export const ALL_PRODUCT_REQUEST = "ALL PROUDCT REQUEST";
export const ALL_PRODUCT_SUCCESS = "ALL PROUDCT SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL PROUDCT FAIL";
export const CLEAR_ERRORS="CLEAR ERRORS"